# Generated by Django 2.0.1 on 2018-01-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuessNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=10)),
                ('user_pwd', models.CharField(max_length=10)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
