# Generated by Django 2.0.1 on 2018-01-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuessNumbers',
            new_name='UserData',
        ),
    ]
